### ISSUE TITLE
Question sur adresse privée

### ISSUE THREAD

**Issue by kingdcreations** [adblanc/netwhat42-train#1]
![gneh](https://user-images.githubusercontent.com/29966027/67711675-c4aaa480-f9c2-11e9-9488-1eba8cfda157.png)

Salut, cette question me semble erronée, je fais peut être erreur, c'est juste histoire d’être sur...

**Comment by adblanc** [comment]
Salut, mes connaissances restent limitées à netwhat en réseau néanmoins sur
internet j'ai pu voir une plage d'adresse ip privées allant de 172.16.0.0 à
172.31.255.255.
Si tu peux m'éclairer afin que je modifie l'éventuelle erreur je veux bien
! :)

**Comment by kingdcreations** [comment]
C'est bien le problème, j'ai répondu 172.16.0.2 qui appartient a la plage d'adresse ip privées allant de 172.16.0.0 à 172.31.255.255 mais le programme m'annonce que ma réponse est fausse comme dans le screenshot envoyé. Il me dit aussi que la bonne réponse est 172.32.0.5 qui n'est pas dans la plage citée precedement. ^^'

**Comment by adblanc** [comment]
Ah oui clairement je n'avais pas bien compris le screen, je fix ça merci
beaucoup et bon courage pour le QCM ;)

**Comment by kingdcreations** [comment]
Merci!!
