### ISSUE TITLE
Bonne réponse erronée?

### ISSUE THREAD

**Issue by djfg0** [adblanc/netwhat42-train#4]
À la question "Quelle classe d'adresse IP a plus d'adresses d'hôtes disponibles par défaut ?"
La réponse serait "UNE"...
Elle existe réellement cette classe? J'en trouve aucune trace :/

**Comment by adblanc** [comment]
je crois qu'il s'agit d'une autre appellation de la classe A malgré le fait que moi non plus je n'ai rien trouvé à ce sujet
